name       : python-sortedcontainers
version    : 2.1.0
release    : 4
source     :
    - https://github.com/grantjenks/python-sortedcontainers/archive/v2.1.0.tar.gz : ecd1ed41968d61d49e2ee2d1a852b452535c2edadaac78147fee815610bc845d
license    : Apache-2.0
component  : programming.python
summary    : Python Sorted Container Types
description: |
    SortedContainers is an Apache2 licensed sorted collections library, written in pure-Python, and fast as C-extensions.
builddeps  :
    - pkgconfig(python3)
setup      : |
    %python3_setup
install    : |
    %python3_install
