name       : python-sortedcontainers
version    : 2.2.2
release    : 5
source     :
    - https://github.com/grantjenks/python-sortedcontainers/archive/v2.2.2.tar.gz : abc6321d987f081f5fa94104ba1da251ed35a32e91865840049898b6390929ef
homepage   : https://github.com/grantjenks/python-sortedcontainers
license    : Apache-2.0
component  : programming.python
summary    : Python Sorted Container Types
description: |
    SortedContainers is an Apache2 licensed sorted collections library, written in pure-Python, and fast as C-extensions.
builddeps  :
    - pkgconfig(python3)
    - matplotlib
    - python-pytest
    - scipy
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pushd py3build/tests
        PYTHONPATH=$installdir/usr/lib/python%python3_version%/site-packages pytest3
    popd
