name       : python-sortedcontainers
version    : 2.3.0
release    : 6
source     :
    - https://github.com/grantjenks/python-sortedcontainers/archive/v2.3.0.tar.gz : d2525693ed36f5651ca42aba1feedb3fe31899ae8385c339da679bcce158d0dd
homepage   : https://github.com/grantjenks/python-sortedcontainers
license    : Apache-2.0
component  : programming.python
summary    : Python Sorted Container Types
description: |
    SortedContainers is an Apache2 licensed sorted collections library, written in pure-Python, and fast as C-extensions.
builddeps  :
    - pkgconfig(python3)
    - matplotlib
    - python-pytest
    - scipy
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pushd py3build/tests
        PYTHONPATH=$installdir/usr/lib/python%python3_version%/site-packages pytest3
    popd
