name       : python-sortedcontainers
version    : 1.5.7
release    : 1
source     :
    - https://github.com/grantjenks/sorted_containers/archive/v1.5.7.tar.gz : 44bcc06360ceab9ee533e76973811c870979bce6938410dbc2f26876a92285b2
license    : Apache-2.0
component  : programming.python
summary    : Python Sorted Container Types
description: |
    SortedContainers is an Apache2 licensed sorted collections library, written in pure-Python, and fast as C-extensions.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
